from pathlib import Path


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    if text.count(old) != 1:
        raise SystemExit(f"{label}: expected exactly one anchor, found {text.count(old)}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


# Desktop persistence: use one SQLite statement for put-if-empty and one
# compare-and-clear statement. Separate DesktopChatDb connections therefore
# serialize through SQLite instead of a read-then-upsert race.
db_path = Path("desktop/composeApp/src/main/kotlin/dk/ternedal/modelrig/desktop/data/DesktopChatDb.kt")
old = '''    fun putSetting(key: String, value: String) {\n        val stored = if (key in CREDENTIAL_SETTING_KEYS && value.isNotEmpty()) {\n            protectCredential(value)\n        } else {\n            value\n        }\n        putRawSetting(storageKey(key), stored)\n    }\n\n    private fun storageKey(key: String): String {\n'''
new = '''    fun putSetting(key: String, value: String) {\n        val stored = if (key in CREDENTIAL_SETTING_KEYS && value.isNotEmpty()) {\n            protectCredential(value)\n        } else {\n            value\n        }\n        putRawSetting(storageKey(key), stored)\n    }\n\n    /** Atomically reserve an unprotected setting only while its slot is empty. */\n    internal fun reserveSettingIfEmpty(key: String, value: String): Boolean {\n        require(key !in CREDENTIAL_SETTING_KEYS) { "credential settings require protected writes" }\n        require(value.isNotEmpty()) { "reserved setting value must be non-empty" }\n        val resolvedKey = storageKey(key)\n        return synchronized(conn) {\n            conn.prepareStatement(\n                "INSERT INTO setting(key, value) VALUES(?, ?) " +\n                    "ON CONFLICT(key) DO UPDATE SET value = excluded.value WHERE setting.value = ''",\n            ).use { st ->\n                st.setString(1, resolvedKey)\n                st.setString(2, value)\n                st.executeUpdate() == 1\n            }\n        }\n    }\n\n    /** Clear only the exact unprotected setting authority that this caller owns. */\n    internal fun clearSettingIfEquals(key: String, expectedValue: String): Boolean {\n        require(key !in CREDENTIAL_SETTING_KEYS) { "credential settings require protected writes" }\n        require(expectedValue.isNotEmpty()) { "expected setting value must be non-empty" }\n        val resolvedKey = storageKey(key)\n        return synchronized(conn) {\n            conn.prepareStatement(\n                "UPDATE setting SET value = '' WHERE key = ? AND value = ?",\n            ).use { st ->\n                st.setString(1, resolvedKey)\n                st.setString(2, expectedValue)\n                st.executeUpdate() == 1\n            }\n        }\n    }\n\n    private fun storageKey(key: String): String {\n'''
replace_once(db_path, old, new, "DesktopChatDb atomic setting helpers")

# Desktop recovery-store API exposes only authority-safe reservation/clearing.
desktop_store = Path("desktop/composeApp/src/main/kotlin/dk/ternedal/modelrig/desktop/data/Agent3ReviewedStartRecoveryStore.kt")
desktop_store.write_text('''package dk.ternedal.modelrig.desktop.data\n\n/** Separate URL-scoped persistence for reviewed Start; task-surface authority is never reused. */\nclass Agent3ReviewedStartRecoveryStore(private val db: DesktopChatDb) {\n    fun read(baseUrl: String?): String? = agent3ReviewedStartRecoveryStorageKey(baseUrl)\n        ?.let(db::getSetting)\n        ?.trim()\n        ?.takeIf { it.isNotEmpty() }\n\n    /** Acquire the rig slot without replacing another process' unresolved Start authority. */\n    fun reserve(baseUrl: String?, encodedAuthority: String?): Boolean {\n        val key = agent3ReviewedStartRecoveryStorageKey(baseUrl) ?: return false\n        val normalized = encodedAuthority?.trim()?.takeIf { it.isNotEmpty() } ?: return false\n        return runCatching { db.reserveSettingIfEmpty(key, normalized) }.getOrDefault(false)\n    }\n\n    /** Clear only if the slot still contains this exact originating authority. */\n    fun clearIfMatches(baseUrl: String?, encodedAuthority: String?): Boolean {\n        val key = agent3ReviewedStartRecoveryStorageKey(baseUrl) ?: return false\n        val normalized = encodedAuthority?.trim()?.takeIf { it.isNotEmpty() } ?: return false\n        return runCatching { db.clearSettingIfEquals(key, normalized) }.getOrDefault(false)\n    }\n}\n\ninternal fun agent3ReviewedStartRecoveryStorageKey(baseUrl: String?): String? =\n    baseUrl\n        ?.trim()\n        ?.trimEnd('/')\n        ?.takeIf { it.isNotEmpty() }\n        ?.let { "$REVIEWED_START_RECOVERY_KEY_PREFIX:$it" }\n\nprivate const val REVIEWED_START_RECOVERY_KEY_PREFIX = "agent3ReviewedStartRecovery"\n''', encoding="utf-8")

# Android SharedPreferences is process-local; serialize screen instances through
# one lock and use the same exact-authority semantics. Android multi-process
# SharedPreferences is not an authority model used by this app.
android_store = Path("android/app/src/main/java/dk/ternedal/modelrig/data/Agent3ReviewedStartRecoveryStore.kt")
android_store.write_text('''package dk.ternedal.modelrig.data\n\nimport android.content.Context\n\n/** URL-scoped storage for the opaque reviewed-Start recovery authority record. */\nclass Agent3ReviewedStartRecoveryStore(context: Context) {\n    private val prefs = context.getSharedPreferences("modelrig", Context.MODE_PRIVATE)\n\n    fun read(baseUrl: String?): String? = agent3ReviewedStartRecoveryStorageKey(baseUrl)\n        ?.let { prefs.getString(it, null) }\n        ?.trim()\n        ?.takeIf { it.isNotEmpty() }\n\n    /** Acquire the rig slot without replacing another screen's unresolved Start authority. */\n    fun reserve(baseUrl: String?, encodedAuthority: String?): Boolean {\n        val key = agent3ReviewedStartRecoveryStorageKey(baseUrl) ?: return false\n        val normalized = encodedAuthority?.trim()?.takeIf { it.isNotEmpty() } ?: return false\n        return synchronized(SLOT_LOCK) {\n            val current = prefs.getString(key, null)?.trim()?.takeIf { it.isNotEmpty() }\n            if (current != null) false else prefs.edit().putString(key, normalized).commit()\n        }\n    }\n\n    /** Clear only if this screen still owns the exact authority stored in the rig slot. */\n    fun clearIfMatches(baseUrl: String?, encodedAuthority: String?): Boolean {\n        val key = agent3ReviewedStartRecoveryStorageKey(baseUrl) ?: return false\n        val normalized = encodedAuthority?.trim()?.takeIf { it.isNotEmpty() } ?: return false\n        return synchronized(SLOT_LOCK) {\n            val current = prefs.getString(key, null)?.trim()?.takeIf { it.isNotEmpty() }\n            if (current != normalized) false else prefs.edit().remove(key).commit()\n        }\n    }\n\n    private companion object {\n        val SLOT_LOCK = Any()\n    }\n}\n\ninternal fun agent3ReviewedStartRecoveryStorageKey(baseUrl: String?): String? =\n    baseUrl\n        ?.trim()\n        ?.trimEnd('/')\n        ?.takeIf { it.isNotEmpty() }\n        ?.let { "$REVIEWED_START_RECOVERY_KEY_PREFIX:$it" }\n\nprivate const val REVIEWED_START_RECOVERY_KEY_PREFIX = "agent3_reviewed_start_recovery"\n''', encoding="utf-8")

# Desktop UI: reserve before network I/O; completion/refusal may clear only its
# own authority. A failed conditional clear stays fail-closed and reloads the
# slot for presentation rather than pretending it was cleared.
desktop_app = Path("desktop/composeApp/src/main/kotlin/dk/ternedal/modelrig/desktop/Agent3ReviewDevApp.kt")
old = '''            val cleared = recoveryStore.write(connection.baseUrl, null)\n            if (!Agent3DevInteractionPolicy.canPublishForConnection(connection, currentConnectionOrNull())) {\n                return\n            }\n            run = envelope.run\n            review = envelope.readReview\n            if (cleared) {\n                pendingStartRecovery = null\n                startRecoveryUnresolved = false\n            } else {\n                pendingStartRecovery = authority\n                startRecoveryUnresolved = true\n                error = "Run blev valideret, men den lokale Start-recovery kunne ikke ryddes. Samme plan kan sikkert gendannes igen."\n            }\n'''
new = '''            val cleared = recoveryStore.clearIfMatches(connection.baseUrl, authority.encode())\n            if (!Agent3DevInteractionPolicy.canPublishForConnection(connection, currentConnectionOrNull())) {\n                return\n            }\n            run = envelope.run\n            review = envelope.readReview\n            if (cleared) {\n                pendingStartRecovery = null\n                startRecoveryUnresolved = false\n            } else {\n                val currentRaw = recoveryStore.read(connection.baseUrl)\n                pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n                startRecoveryUnresolved = true\n                error = "Run blev valideret, men recovery-slotten kunne ikke ryddes som den samme authority. Nye Starts forbliver blokeret."\n            }\n'''
replace_once(desktop_app, old, new, "desktop success conditional clear")
old = '''                val cleared = recoveryStore.write(connection.baseUrl, null)\n                if (!Agent3DevInteractionPolicy.canPublishForConnection(connection, currentConnectionOrNull())) {\n                    return\n                }\n                if (cleared) {\n                    pendingStartRecovery = null\n                    startRecoveryUnresolved = false\n                } else {\n                    startRecoveryUnresolved = true\n                }\n'''
new = '''                val cleared = recoveryStore.clearIfMatches(connection.baseUrl, authority.encode())\n                if (!Agent3DevInteractionPolicy.canPublishForConnection(connection, currentConnectionOrNull())) {\n                    return\n                }\n                if (cleared) {\n                    pendingStartRecovery = null\n                    startRecoveryUnresolved = false\n                } else {\n                    val currentRaw = recoveryStore.read(connection.baseUrl)\n                    pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n                    startRecoveryUnresolved = true\n                }\n'''
replace_once(desktop_app, old, new, "desktop refusal conditional clear")
old = '''            if (!recoveryStore.write(connection.baseUrl, authority.encode())) {\n                error = "Start blev ikke sendt, fordi recovery-authority ikke kunne gemmes sikkert lokalt."\n                return\n            }\n'''
new = '''            if (!recoveryStore.reserve(connection.baseUrl, authority.encode())) {\n                val currentRaw = recoveryStore.read(connection.baseUrl)\n                pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n                startRecoveryUnresolved = true\n                error = "Start blev ikke sendt, fordi en unresolved recovery-authority allerede ejer denne rig-slot eller slotten ikke kunne reserveres sikkert."\n                return\n            }\n'''
replace_once(desktop_app, old, new, "desktop atomic reserve")

# Android UI mirrors the same authority-safe lifecycle.
android_app = Path("android/app/src/main/java/dk/ternedal/modelrig/ui/Agent3ReviewScreen.kt")
old = '''        if (recoveryStore.write(connection.baseUrl, null)) {\n            pendingStartRecovery = null\n            startRecoveryUnresolved = false\n        } else {\n            pendingStartRecovery = authority\n            startRecoveryUnresolved = true\n            error = "Run blev valideret, men den lokale Start-recovery kunne ikke ryddes. Samme plan kan sikkert gendannes igen."\n        }\n'''
new = '''        if (recoveryStore.clearIfMatches(connection.baseUrl, authority.encode())) {\n            pendingStartRecovery = null\n            startRecoveryUnresolved = false\n        } else {\n            val currentRaw = recoveryStore.read(connection.baseUrl)\n            pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n            startRecoveryUnresolved = true\n            error = "Run blev valideret, men recovery-slotten kunne ikke ryddes som den samme authority. Nye Starts forbliver blokeret."\n        }\n'''
replace_once(android_app, old, new, "android success conditional clear")
old = '''            val cleared = recoveryStore.write(connection.baseUrl, null)\n            if (cleared) {\n                pendingStartRecovery = null\n                startRecoveryUnresolved = false\n            } else {\n                startRecoveryUnresolved = true\n            }\n'''
new = '''            val cleared = recoveryStore.clearIfMatches(connection.baseUrl, authority.encode())\n            if (cleared) {\n                pendingStartRecovery = null\n                startRecoveryUnresolved = false\n            } else {\n                val currentRaw = recoveryStore.read(connection.baseUrl)\n                pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n                startRecoveryUnresolved = true\n            }\n'''
replace_once(android_app, old, new, "android refusal conditional clear")
old = '''        if (!recoveryStore.write(connection.baseUrl, authority.encode())) {\n            error = "Start blev ikke sendt, fordi recovery-authority ikke kunne gemmes sikkert lokalt."\n            return\n        }\n'''
new = '''        if (!recoveryStore.reserve(connection.baseUrl, authority.encode())) {\n            val currentRaw = recoveryStore.read(connection.baseUrl)\n            pendingStartRecovery = Agent3ReviewedStartRecoveryAuthority.decode(currentRaw)\n            startRecoveryUnresolved = true\n            error = "Start blev ikke sendt, fordi en unresolved recovery-authority allerede ejer denne rig-slot eller slotten ikke kunne reserveres sikkert."\n            return\n        }\n'''
replace_once(android_app, old, new, "android atomic reserve")

# Desktop regression: two independent JDBC connections model separate desktop
# processes sharing ~/.modelrig/modelrig.db. The second authority cannot replace
# or clear the first one.
desktop_test = Path("desktop/composeApp/src/test/kotlin/dk/ternedal/modelrig/desktop/data/Agent3ReviewedStartRecoveryStoreTest.kt")
desktop_test.write_text('''package dk.ternedal.modelrig.desktop.data\n\nimport java.nio.file.Files\nimport kotlin.io.path.deleteIfExists\nimport kotlin.test.Test\nimport kotlin.test.assertEquals\nimport kotlin.test.assertFalse\nimport kotlin.test.assertNotEquals\nimport kotlin.test.assertNull\nimport kotlin.test.assertTrue\n\nclass Agent3ReviewedStartRecoveryStoreTest {\n    @Test\n    fun reviewedRecoveryKeyIsNormalizedAndRigScoped() {\n        assertEquals(\n            agent3ReviewedStartRecoveryStorageKey(" https://rig.example/ "),\n            agent3ReviewedStartRecoveryStorageKey("https://rig.example"),\n        )\n        assertNotEquals(\n            agent3ReviewedStartRecoveryStorageKey("https://rig-a.example"),\n            agent3ReviewedStartRecoveryStorageKey("https://rig-b.example"),\n        )\n        assertNull(agent3ReviewedStartRecoveryStorageKey("  "))\n    }\n\n    @Test\n    fun reviewedRecoverySlotIsAtomicAcrossIndependentDatabaseConnections() {\n        val path = Files.createTempFile("modelrig-reviewed-start-slot-", ".db")\n        try {\n            DesktopChatDb(path.toString()).use { dbA ->\n                DesktopChatDb(path.toString()).use { dbB ->\n                    val storeA = Agent3ReviewedStartRecoveryStore(dbA)\n                    val storeB = Agent3ReviewedStartRecoveryStore(dbB)\n                    val url = "https://rig.example"\n                    val authorityA = "authority-a"\n                    val authorityB = "authority-b"\n\n                    assertTrue(storeA.reserve(url, authorityA))\n                    assertFalse(storeB.reserve(url, authorityB))\n                    assertEquals(authorityA, storeB.read(url))\n\n                    assertFalse(storeB.clearIfMatches(url, authorityB))\n                    assertEquals(authorityA, storeA.read(url))\n                    assertTrue(storeA.clearIfMatches(url, authorityA))\n                    assertNull(storeB.read(url))\n\n                    assertTrue(storeB.reserve(url, authorityB))\n                    assertEquals(authorityB, storeA.read(url))\n                }\n            }\n        } finally {\n            path.deleteIfExists()\n        }\n    }\n}\n''', encoding="utf-8")

# Android regression uses two store instances backed by the same SharedPreferences
# file, matching concurrent screen instances in one app process.
android_test = Path("android/app/src/test/java/dk/ternedal/modelrig/data/Agent3ReviewedStartRecoveryStoreTest.kt")
android_test.write_text('''package dk.ternedal.modelrig.data\n\nimport android.content.Context\nimport org.junit.Assert.assertEquals\nimport org.junit.Assert.assertFalse\nimport org.junit.Assert.assertNotEquals\nimport org.junit.Assert.assertNull\nimport org.junit.Assert.assertTrue\nimport org.junit.Test\nimport org.junit.runner.RunWith\nimport org.robolectric.RobolectricTestRunner\nimport org.robolectric.RuntimeEnvironment\n\n@RunWith(RobolectricTestRunner::class)\nclass Agent3ReviewedStartRecoveryStoreTest {\n    @Test\n    fun `reviewed recovery key is normalized and rig scoped`() {\n        assertEquals(\n            agent3ReviewedStartRecoveryStorageKey(" https://rig.example/ "),\n            agent3ReviewedStartRecoveryStorageKey("https://rig.example"),\n        )\n        assertNotEquals(\n            agent3ReviewedStartRecoveryStorageKey("https://rig-a.example"),\n            agent3ReviewedStartRecoveryStorageKey("https://rig-b.example"),\n        )\n        assertNull(agent3ReviewedStartRecoveryStorageKey("  "))\n    }\n\n    @Test\n    fun `reviewed recovery slot is reserved and cleared only by exact authority`() {\n        val context = RuntimeEnvironment.getApplication()\n        context.getSharedPreferences("modelrig", Context.MODE_PRIVATE).edit().clear().commit()\n        val storeA = Agent3ReviewedStartRecoveryStore(context)\n        val storeB = Agent3ReviewedStartRecoveryStore(context)\n        val url = "https://rig.example"\n\n        assertTrue(storeA.reserve(url, "authority-a"))\n        assertFalse(storeB.reserve(url, "authority-b"))\n        assertEquals("authority-a", storeB.read(url))\n        assertFalse(storeB.clearIfMatches(url, "authority-b"))\n        assertEquals("authority-a", storeA.read(url))\n        assertTrue(storeA.clearIfMatches(url, "authority-a"))\n        assertNull(storeB.read(url))\n        assertTrue(storeB.reserve(url, "authority-b"))\n    }\n}\n''', encoding="utf-8")

print("applied P1q atomic reviewed-Start recovery-slot fix")
