"""Public host-pinned facade for ADR-DC-045 local-commit authorization admission."""
from __future__ import annotations
from . import _improvement_pilot_exact_task_local_commit_authorization_admission_impl as _implementation
from ._improvement_pilot_exact_task_local_commit_authorization_admission_production_boundary import install_pilot_exact_task_local_commit_authorization_admission_production_boundary
install_pilot_exact_task_local_commit_authorization_admission_production_boundary(_implementation)
PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_RECEIPT_SCHEMA = _implementation.PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_RECEIPT_SCHEMA
PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_AUTHORITY = _implementation.PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_AUTHORITY
PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_LEDGER_SCOPE = _implementation.PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_LEDGER_SCOPE
PilotExactTaskLocalCommitAuthorizationAdmissionError = _implementation.PilotExactTaskLocalCommitAuthorizationAdmissionError
PilotExactTaskLocalCommitAuthorizationAdmissionReceipt = _implementation.PilotExactTaskLocalCommitAuthorizationAdmissionReceipt
admit_pilot_exact_task_local_commit_authorization = _implementation.admit_pilot_exact_task_local_commit_authorization
require_fresh_local_commit_authorization_proof_identity = _implementation.require_fresh_local_commit_authorization_proof_identity
_admission_key = _implementation._admission_key
_PilotExactTaskLocalCommitAuthorizationAdmissionLedger = _implementation._PilotExactTaskLocalCommitAuthorizationAdmissionLedger
_admit_verified_pilot_exact_task_local_commit_authorization = _implementation._admit_verified_pilot_exact_task_local_commit_authorization
_get_live_local_commit_authorization_admission_inputs = _implementation._get_live_local_commit_authorization_admission_inputs
__all__ = ['PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_RECEIPT_SCHEMA', 'PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_AUTHORITY', 'PILOT_EXACT_TASK_LOCAL_COMMIT_AUTHORIZATION_ADMISSION_LEDGER_SCOPE', 'PilotExactTaskLocalCommitAuthorizationAdmissionError', 'PilotExactTaskLocalCommitAuthorizationAdmissionReceipt', 'admit_pilot_exact_task_local_commit_authorization']
del install_pilot_exact_task_local_commit_authorization_admission_production_boundary
