"""Public host-pinned facade for ADR-DC-052 remote credential capability."""
from __future__ import annotations

from . import _improvement_pilot_exact_task_remote_publication_credential_capability_impl as _implementation
from ._improvement_pilot_exact_task_remote_publication_credential_capability_production_boundary import (
    install_pilot_exact_task_remote_publication_credential_capability_production_boundary,
)

install_pilot_exact_task_remote_publication_credential_capability_production_boundary(
    _implementation
)

PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_SCHEMA = (
    _implementation.PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_SCHEMA
)
PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_AUTHORITY = (
    _implementation.PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_AUTHORITY
)
PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_PROTOCOL = (
    _implementation.PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_PROTOCOL
)
PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_SOURCE = (
    _implementation.PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_SOURCE
)
PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_TRANSPORT = (
    _implementation.PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_TRANSPORT
)
PilotExactTaskRemotePublicationCredentialCapabilityError = (
    _implementation.PilotExactTaskRemotePublicationCredentialCapabilityError
)
PilotExactTaskRemotePublicationCredentialCapability = (
    _implementation.PilotExactTaskRemotePublicationCredentialCapability
)
materialize_pilot_exact_task_remote_publication_credential_capability = (
    _implementation.materialize_pilot_exact_task_remote_publication_credential_capability
)

# Deterministic support seams only; production broker selection is host-pinned above.
_require_live_reservation = _implementation._require_live_reservation
_descriptor = _implementation._descriptor
_materialize_verified_pilot_exact_task_remote_publication_credential_capability = (
    _implementation._materialize_verified_pilot_exact_task_remote_publication_credential_capability
)
_get_live_remote_publication_credential_capability_inputs = (
    _implementation._get_live_remote_publication_credential_capability_inputs
)

__all__ = [
    "PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_SCHEMA",
    "PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_CAPABILITY_AUTHORITY",
    "PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_PROTOCOL",
    "PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_SOURCE",
    "PILOT_EXACT_TASK_REMOTE_PUBLICATION_CREDENTIAL_SECRET_TRANSPORT",
    "PilotExactTaskRemotePublicationCredentialCapabilityError",
    "PilotExactTaskRemotePublicationCredentialCapability",
    "materialize_pilot_exact_task_remote_publication_credential_capability",
]

del install_pilot_exact_task_remote_publication_credential_capability_production_boundary
