"""Public host-pinned facade for ADR-DC-089 strict-synced review-thread capability."""
from __future__ import annotations

from . import _improvement_pilot_exact_task_pr_strict_synced_review_thread_credential_capability_impl as _implementation
from ._improvement_pilot_exact_task_pr_strict_synced_review_thread_credential_capability_production_boundary import (
    install_pilot_exact_task_pr_strict_synced_review_thread_credential_capability_production_boundary,
)

install_pilot_exact_task_pr_strict_synced_review_thread_credential_capability_production_boundary(
    _implementation
)

PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_SCHEMA = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_SCHEMA
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_AUTHORITY = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_AUTHORITY
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_PROTOCOL = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_PROTOCOL
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_OPERATION = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_OPERATION
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_SOURCE = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_SOURCE
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_TRANSPORT = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_TRANSPORT
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_ENDPOINT = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_ENDPOINT
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_ACCOUNT = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_ACCOUNT
PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_MAX_PREFLIGHT_AGE_SECONDS = _implementation.PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_MAX_PREFLIGHT_AGE_SECONDS
PilotExactTaskPrStrictSyncedReviewThreadCredentialCapabilityError = _implementation.PilotExactTaskPrStrictSyncedReviewThreadCredentialCapabilityError
PilotExactTaskPrStrictSyncedReviewThreadCredentialCapability = _implementation.PilotExactTaskPrStrictSyncedReviewThreadCredentialCapability
materialize_pilot_exact_task_pr_strict_synced_review_thread_credential_capability = _implementation.materialize_pilot_exact_task_pr_strict_synced_review_thread_credential_capability

_require_live_strict_sync = _implementation._require_live_strict_sync
_require_preflight_window = _implementation._require_preflight_window
_descriptor = _implementation._descriptor
_query_sha256 = _implementation._query_sha256
_materialize_verified_pilot_exact_task_pr_strict_synced_review_thread_credential_capability = _implementation._materialize_verified_pilot_exact_task_pr_strict_synced_review_thread_credential_capability
_get_live_pr_strict_synced_review_thread_credential_capability_inputs = _implementation._get_live_pr_strict_synced_review_thread_credential_capability_inputs

__all__ = [
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_SCHEMA",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_CAPABILITY_AUTHORITY",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_PROTOCOL",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_OPERATION",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_SOURCE",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_SECRET_TRANSPORT",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_GRAPHQL_ENDPOINT",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_CREDENTIAL_ACCOUNT",
    "PILOT_EXACT_TASK_PR_STRICT_SYNCED_REVIEW_THREAD_MAX_PREFLIGHT_AGE_SECONDS",
    "PilotExactTaskPrStrictSyncedReviewThreadCredentialCapabilityError",
    "PilotExactTaskPrStrictSyncedReviewThreadCredentialCapability",
    "materialize_pilot_exact_task_pr_strict_synced_review_thread_credential_capability",
]

del install_pilot_exact_task_pr_strict_synced_review_thread_credential_capability_production_boundary
