"""Agent 4 autonomous campaign orchestration foundation."""

from .checkpoint import (
    CampaignCheckpoint,
    CampaignCheckpointService,
    CheckpointConflictError,
    CheckpointLifecycleError,
    CheckpointStoreError,
    JsonCheckpointStore,
)
from .contracts import (
    CampaignCheckpointStore,
    CampaignEventHandler,
    CampaignEventPublisher,
    CampaignEventRecorder,
    CampaignEventSubscriber,
    CampaignExecutor,
    CampaignRepository,
    CampaignResourceLeaseManager,
    CampaignResourceResolver,
    Clock,
    IdGenerator,
)
from .domain import (
    CampaignEvent,
    CampaignEventKind,
    CampaignPriority,
    CampaignRecord,
    CampaignSpec,
    CampaignState,
    CampaignStatus,
    CampaignTransitionError,
    CampaignValidationError,
    transition_campaign,
    utc_now,
)
from .event_bus import CampaignEventOrderError, InMemoryCampaignEventBus
from .health import (
    CampaignHealthObservation,
    CampaignWatchdogPolicy,
    HealthLevel,
    WatchdogAction,
    WatchdogDecision,
    WatchdogPolicy,
)
from .recovery import (
    CampaignRecoveryDecision,
    CampaignRecoveryReport,
    CampaignRecoveryService,
    RecoveryAction,
)
from .repository import CampaignRepositoryError, JsonCampaignRepository
from .retry import (
    CampaignRetryPlanner,
    DefaultRetryClassifier,
    FailureDescriptor,
    RetryCategory,
    RetryClassifier,
    RetryDecision,
    RetryDisposition,
    RetryPolicy,
)
from .retry_scheduling import (
    CampaignRetrySchedulingService,
    RetryScheduleResult,
)
from .resource_admission import (
    CampaignResourceBlockedError,
    ResourceAwareCampaignSchedulerService,
    ResourceDispatchResult,
)
from .resources import (
    InMemoryResourceLeaseManager,
    ResourceLease,
    ResourceLeaseConflictError,
    ResourceLeaseError,
    ResourceLeaseNotFoundError,
    ResourceSnapshot,
)
from .scheduler import CampaignQueue, DuplicateCampaignError
from .service import (
    CampaignConflictError,
    CampaignNotFoundError,
    CampaignSchedulerService,
    DispatchResult,
    SystemClock,
)

__all__ = [
    "CampaignCheckpoint",
    "CampaignCheckpointService",
    "CampaignCheckpointStore",
    "CampaignConflictError",
    "CampaignEvent",
    "CampaignEventHandler",
    "CampaignEventKind",
    "CampaignEventOrderError",
    "CampaignEventPublisher",
    "CampaignEventRecorder",
    "CampaignEventSubscriber",
    "CampaignExecutor",
    "CampaignNotFoundError",
    "WatchdogPolicy",
    "WatchdogDecision",
    "WatchdogAction",
    "HealthLevel",
    "CampaignWatchdogPolicy",
    "CampaignHealthObservation",
    "CampaignPriority",
    "CampaignQueue",
    "CampaignRecord",
    "CampaignRecoveryDecision",
    "CampaignRecoveryReport",
    "CampaignRecoveryService",
    "CampaignRepository",
    "CampaignRepositoryError",
    "CampaignResourceBlockedError",
    "CampaignResourceLeaseManager",
    "CampaignResourceResolver",
    "CampaignSchedulerService",
    "RetryPolicy",
    "RetryDisposition",
    "RetryDecision",
    "RetryClassifier",
    "RetryCategory",
    "FailureDescriptor",
    "DefaultRetryClassifier",
    "CampaignRetryPlanner",
    "CampaignRetrySchedulingService",
    "RetryScheduleResult",
    "CampaignSpec",
    "CampaignState",
    "CampaignStatus",
    "CampaignTransitionError",
    "CampaignValidationError",
    "CheckpointConflictError",
    "CheckpointLifecycleError",
    "CheckpointStoreError",
    "Clock",
    "DispatchResult",
    "DuplicateCampaignError",
    "IdGenerator",
    "InMemoryCampaignEventBus",
    "JsonCampaignRepository",
    "JsonCheckpointStore",
    "InMemoryResourceLeaseManager",
    "ResourceDispatchResult",
    "ResourceLease",
    "ResourceLeaseConflictError",
    "ResourceLeaseError",
    "ResourceLeaseNotFoundError",
    "ResourceSnapshot",
    "RecoveryAction",
    "ResourceAwareCampaignSchedulerService",
    "SystemClock",
    "transition_campaign",
    "utc_now",
]
