"""Agent 4 autonomous campaign orchestration foundation."""

from .checkpoint import (
    CampaignCheckpoint,
    CampaignCheckpointService,
    CheckpointConflictError,
    CheckpointLifecycleError,
    CheckpointStoreError,
    JsonCheckpointStore,
)
from .contracts import (
    CampaignCheckpointStore,
    CampaignEventHandler,
    CampaignEventPublisher,
    CampaignEventRecorder,
    CampaignEventSubscriber,
    CampaignExecutor,
    CampaignRepository,
    Clock,
    IdGenerator,
)
from .domain import (
    CampaignEvent,
    CampaignEventKind,
    CampaignPriority,
    CampaignRecord,
    CampaignSpec,
    CampaignState,
    CampaignStatus,
    CampaignTransitionError,
    CampaignValidationError,
    transition_campaign,
    utc_now,
)
from .event_bus import CampaignEventOrderError, InMemoryCampaignEventBus
from .recovery import (
    CampaignRecoveryDecision,
    CampaignRecoveryReport,
    CampaignRecoveryService,
    RecoveryAction,
)
from .repository import CampaignRepositoryError, JsonCampaignRepository
from .resources import (
    InMemoryResourceLeaseManager,
    ResourceLease,
    ResourceLeaseConflictError,
    ResourceLeaseError,
    ResourceLeaseNotFoundError,
    ResourceSnapshot,
)
from .scheduler import CampaignQueue, DuplicateCampaignError
from .service import (
    CampaignConflictError,
    CampaignNotFoundError,
    CampaignSchedulerService,
    DispatchResult,
    SystemClock,
)

__all__ = [
    "CampaignCheckpoint",
    "CampaignCheckpointService",
    "CampaignCheckpointStore",
    "CampaignConflictError",
    "CampaignEvent",
    "CampaignEventHandler",
    "CampaignEventKind",
    "CampaignEventOrderError",
    "CampaignEventPublisher",
    "CampaignEventRecorder",
    "CampaignEventSubscriber",
    "CampaignExecutor",
    "CampaignNotFoundError",
    "CampaignPriority",
    "CampaignQueue",
    "CampaignRecord",
    "CampaignRecoveryDecision",
    "CampaignRecoveryReport",
    "CampaignRecoveryService",
    "CampaignRepository",
    "CampaignRepositoryError",
    "CampaignSchedulerService",
    "CampaignSpec",
    "CampaignState",
    "CampaignStatus",
    "CampaignTransitionError",
    "CampaignValidationError",
    "CheckpointConflictError",
    "CheckpointLifecycleError",
    "CheckpointStoreError",
    "Clock",
    "DispatchResult",
    "DuplicateCampaignError",
    "IdGenerator",
    "InMemoryCampaignEventBus",
    "InMemoryResourceLeaseManager",
    "JsonCampaignRepository",
    "JsonCheckpointStore",
    "RecoveryAction",
    "ResourceLease",
    "ResourceLeaseConflictError",
    "ResourceLeaseError",
    "ResourceLeaseNotFoundError",
    "ResourceSnapshot",
    "SystemClock",
    "transition_campaign",
    "utc_now",
]
