"""Agent 4 autonomous campaign orchestration foundation."""

from .campaign_queue import CampaignQueue, DuplicateCampaignError
from .checkpoint import (
    CampaignCheckpoint,
    CampaignCheckpointService,
    CheckpointConflictError,
    CheckpointLifecycleError,
    CheckpointStoreError,
    JsonCheckpointStore,
)
from .composition import (
    Agent4RuntimeContext,
    Agent4RuntimePaths,
    compose_agent4_runtime,
)
from .contracts import (
    CampaignCheckpointStore,
    CampaignEventHandler,
    CampaignEventPublisher,
    CampaignEventRecorder,
    CampaignEventSubscriber,
    CampaignExecutor,
    CampaignRepository,
    CampaignResourceLeaseManager,
    CampaignResourceResolver,
    CampaignTimelineCursorStore,
    CampaignTimelineStore,
    Clock,
    IdGenerator,
)
from .domain import (
    CampaignEvent,
    CampaignEventKind,
    CampaignPriority,
    CampaignRecord,
    CampaignSpec,
    CampaignState,
    CampaignStatus,
    CampaignTransitionError,
    CampaignValidationError,
    transition_campaign,
    utc_now,
)
from .event_bus import CampaignEventOrderError, InMemoryCampaignEventBus
from .failure_handling import (
    CampaignFailureHandlingService,
    FailureHandlingResult,
)
from .health import (
    CampaignHealthObservation,
    CampaignHealthPolicy,
    HealthDecision,
    HealthInterventionAction,
    HealthLevel,
    HealthPolicy,
)
from .health_intervention import (
    CampaignHealthInterventionCoordinator,
    HealthInterventionCompositionError,
    HealthInterventionExecutionError,
    HealthInterventionHandler,
    HealthInterventionResult,
)
from .health_intervention_adapters import (
    CampaignHealthFailClosedService,
    CheckpointPayloadProvider,
    HealthInterventionAdapterCompositionError,
    HealthInterventionLifecycleService,
    HealthInterventionServiceAdapters,
)
from .operator import (
    MAX_OPERATOR_CAMPAIGNS,
    Agent4CampaignOverview,
    Agent4OperatorReadService,
)
from .projection import (
    CampaignProjectionError,
    CampaignProjectionIntent,
    CampaignProjectionReconciler,
    CampaignProjectionReport,
    CampaignProjectionRepository,
    CampaignProjectionSpec,
    CampaignStateProjectionService,
)
from .recovery import (
    CampaignRecoveryDecision,
    CampaignRecoveryReport,
    CampaignRecoveryService,
    RecoveryAction,
)
from .repository import CampaignRepositoryError, JsonCampaignRepository
from .resource_admission import (
    CampaignResourceBlockedError,
    ResourceAwareCampaignSchedulerService,
    ResourceDispatchResult,
)
from .resources import (
    InMemoryResourceLeaseManager,
    ResourceLease,
    ResourceLeaseConflictError,
    ResourceLeaseError,
    ResourceLeaseNotFoundError,
    ResourceSnapshot,
)
from .retry import (
    CampaignRetryPlanner,
    DefaultRetryClassifier,
    FailureDescriptor,
    RetryCategory,
    RetryClassifier,
    RetryDecision,
    RetryDisposition,
    RetryPolicy,
)
from .service import (
    CampaignConflictError,
    CampaignNotFoundError,
    CampaignSchedulerService,
    DispatchResult,
    SystemClock,
)
from .timeline import (
    CampaignEvidenceReference,
    CampaignTimelineEntry,
    CampaignTimelineVerification,
    JsonCampaignTimelineStore,
    TimelineConflictError,
    TimelineIntegrityError,
    TimelineStoreError,
)
from .timeline_batches import (
    MAX_TIMELINE_DELIVERY_BATCH_SIZE,
    CampaignTimelineBatchDeliveryResult,
    CampaignTimelineBatchDeliveryService,
)
from .timeline_delivery import (
    CampaignTimelineCursor,
    CampaignTimelineDeliveryResult,
    CampaignTimelineDeliveryService,
    JsonCampaignTimelineCursorStore,
    TimelineCursorConflictError,
    TimelineCursorStoreError,
    TimelineDeliveryIntegrityError,
)
from .timeline_delivery_flights import (
    CampaignTimelineDeliveryBusyError,
    CampaignTimelineDeliveryFlight,
    CampaignTimelineDeliveryFlightConflictError,
    CampaignTimelineDeliveryFlightError,
    InMemoryCampaignTimelineDeliverySingleFlight,
    SingleFlightCampaignTimelineDeliveryService,
)
from .timeline_query import (
    MAX_TIMELINE_QUERY_PAGE_SIZE,
    CampaignTimelineQueryCursor,
    CampaignTimelineQueryCursorError,
    CampaignTimelineQueryError,
    CampaignTimelineQueryPage,
    CampaignTimelineQueryService,
)
from .timeline_recorder import TimelineCampaignEventRecorder

__all__ = [
    "Agent4CampaignOverview",
    "Agent4OperatorReadService",
    "Agent4RuntimeContext",
    "Agent4RuntimePaths",
    "CampaignCheckpoint",
    "CampaignCheckpointService",
    "CampaignCheckpointStore",
    "CampaignConflictError",
    "CampaignEvidenceReference",
    "CampaignEvent",
    "CampaignEventHandler",
    "CampaignEventKind",
    "CampaignEventOrderError",
    "CampaignEventPublisher",
    "CampaignEventRecorder",
    "CampaignEventSubscriber",
    "CampaignExecutor",
    "CampaignFailureHandlingService",
    "CampaignHealthFailClosedService",
    "CampaignHealthInterventionCoordinator",
    "CampaignHealthObservation",
    "CampaignHealthPolicy",
    "CampaignNotFoundError",
    "CampaignPriority",
    "CampaignProjectionError",
    "CampaignProjectionIntent",
    "CampaignProjectionReconciler",
    "CampaignProjectionReport",
    "CampaignProjectionRepository",
    "CampaignProjectionSpec",
    "CampaignQueue",
    "CampaignRecord",
    "CampaignRecoveryDecision",
    "CampaignRecoveryReport",
    "CampaignRecoveryService",
    "CampaignRepository",
    "CampaignRepositoryError",
    "CampaignResourceBlockedError",
    "CampaignResourceLeaseManager",
    "CampaignResourceResolver",
    "CampaignRetryPlanner",
    "CampaignSchedulerService",
    "CampaignSpec",
    "CampaignState",
    "CampaignStateProjectionService",
    "CampaignStatus",
    "CampaignTimelineBatchDeliveryResult",
    "CampaignTimelineBatchDeliveryService",
    "CampaignTimelineCursor",
    "CampaignTimelineCursorStore",
    "CampaignTimelineDeliveryBusyError",
    "CampaignTimelineDeliveryFlight",
    "CampaignTimelineDeliveryFlightConflictError",
    "CampaignTimelineDeliveryFlightError",
    "CampaignTimelineDeliveryResult",
    "CampaignTimelineDeliveryService",
    "CampaignTimelineEntry",
    "CampaignTimelineQueryCursor",
    "CampaignTimelineQueryCursorError",
    "CampaignTimelineQueryError",
    "CampaignTimelineQueryPage",
    "CampaignTimelineQueryService",
    "CampaignTimelineStore",
    "CampaignTimelineVerification",
    "CampaignTransitionError",
    "CampaignValidationError",
    "CheckpointConflictError",
    "CheckpointLifecycleError",
    "CheckpointPayloadProvider",
    "CheckpointStoreError",
    "Clock",
    "DefaultRetryClassifier",
    "DispatchResult",
    "DuplicateCampaignError",
    "FailureDescriptor",
    "FailureHandlingResult",
    "HealthDecision",
    "HealthInterventionAction",
    "HealthInterventionAdapterCompositionError",
    "HealthInterventionCompositionError",
    "HealthInterventionExecutionError",
    "HealthInterventionHandler",
    "HealthInterventionLifecycleService",
    "HealthInterventionResult",
    "HealthInterventionServiceAdapters",
    "HealthLevel",
    "HealthPolicy",
    "IdGenerator",
    "InMemoryCampaignEventBus",
    "InMemoryCampaignTimelineDeliverySingleFlight",
    "InMemoryResourceLeaseManager",
    "JsonCampaignRepository",
    "JsonCampaignTimelineCursorStore",
    "JsonCampaignTimelineStore",
    "JsonCheckpointStore",
    "MAX_OPERATOR_CAMPAIGNS",
    "MAX_TIMELINE_DELIVERY_BATCH_SIZE",
    "MAX_TIMELINE_QUERY_PAGE_SIZE",
    "RecoveryAction",
    "ResourceAwareCampaignSchedulerService",
    "ResourceDispatchResult",
    "ResourceLease",
    "ResourceLeaseConflictError",
    "ResourceLeaseError",
    "ResourceLeaseNotFoundError",
    "ResourceSnapshot",
    "RetryCategory",
    "RetryClassifier",
    "RetryDecision",
    "RetryDisposition",
    "RetryPolicy",
    "SingleFlightCampaignTimelineDeliveryService",
    "SystemClock",
    "TimelineCampaignEventRecorder",
    "TimelineConflictError",
    "TimelineCursorConflictError",
    "TimelineCursorStoreError",
    "TimelineDeliveryIntegrityError",
    "TimelineIntegrityError",
    "TimelineStoreError",
    "compose_agent4_runtime",
    "transition_campaign",
    "utc_now",
]
