#!/usr/bin/env python3
"""Stamp worker source + commit identity before PyInstaller packing.

The existing source fingerprint remains the behavioural identity used by the
physical-validation chain.  ADR-DC-084 additionally needs the exact Git commit
that produced the packed worker, so both values are written into the generated
stamp immediately before PyInstaller runs.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "worker"))

from app.build_identity import _hash_source_tree  # noqa: E402

STAMP = ROOT / "worker" / "app" / "_build_stamp.py"
_HEX40 = re.compile(r"^[0-9a-f]{40}$")


def _commit_sha() -> str:
    supplied = os.getenv("GITHUB_SHA", "").strip().lower()
    if supplied:
        if _HEX40.fullmatch(supplied) is None:
            raise RuntimeError("GITHUB_SHA is not one canonical 40-char commit SHA")
        return supplied
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise RuntimeError("cannot determine exact worker build commit") from exc
    value = completed.stdout.strip().lower()
    if _HEX40.fullmatch(value) is None:
        raise RuntimeError("git rev-parse returned a non-canonical commit SHA")
    return value


def main() -> int:
    digest = _hash_source_tree()
    commit = _commit_sha()
    STAMP.write_text(
        '"""Generated by scripts/stamp_build_identity.py. Do not edit, do not commit.\n\n'
        "This is what the packed worker answers when validation asks which code\n"
        "and exact Git commit it is running. The stamp is excluded from the\n"
        "source hash it carries.\n"
        '"""\n'
        f'CODE_SHA256 = "{digest}"\n'
        f'COMMIT_SHA = "{commit}"\n',
        encoding="utf-8",
    )
    print(
        f"stamped {STAMP.relative_to(ROOT)} with code={digest} commit={commit}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
