#!/usr/bin/env python3
"""Stamp the source-tree fingerprint into the worker before packing (F-607).

Run immediately before PyInstaller. A packed worker has no source tree to hash,
and hashing its own exe answers a different question than the readiness page
asks -- the page runs from a checkout and hashes the code. Two hashes of
different things can never match, which made code_match False forever on the
real appliance and physical validation impossible to pass.

So the identity is decided here, once, from the code, and travels into the
binary. Same code, same answer, whichever side asks.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "worker"))

from app.build_identity import _hash_source_tree  # noqa: E402

STAMP = ROOT / "worker" / "app" / "_build_stamp.py"


def main() -> int:
    digest = _hash_source_tree()
    STAMP.write_text(
        '"""Generated by scripts/stamp_build_identity.py. Do not edit, do not commit.\n\n'
        "This is what the packed worker answers when the validation gate asks\n"
        "which code it is running. It is excluded from the hash it carries --\n"
        "otherwise stamping the tree would change the tree it just measured.\n"
        '"""\n'
        f'CODE_SHA256 = "{digest}"\n',
        encoding="utf-8",
    )
    print(f"stamped {STAMP.relative_to(ROOT)} with {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
